### ISSUE TITLE
save.genotypes fails when type="t"

### ISSUE THREAD

**Issue by ayelet10** [vllrs/genomicSimulation#5]
Hello! 
I am using genomicSimulation v.2.2,  R crashes when I try to use the type="t" option in save.genotypes, but using type="r" works fine. It happens with large (>30k markers) as well as with small (10 markers) data files.
Thank you in advance!
Ayelet

**Comment by vllrs** [comment]
Thanks for the report, I believe I've been able to track down the bug. 

Version 0.2.4 fixes the issue, but if you don't want to update to that, here's a minor modification of release v0.2.2 with the fix implemented:

[genomicSimulation_0.2.2.002.tar.gz](https://github.com/vllrs/genomicSimulation/files/14234437/genomicSimulation_0.2.2.002.tar.gz)
[genomicSimulation_0.2.2.002.zip](https://github.com/vllrs/genomicSimulation/files/14234438/genomicSimulation_0.2.2.002.zip)

Let me know if that works?
