### ISSUE TITLE
phasing information

### ISSUE THREAD

**Issue by jguo9527** [vllrs/genomicSimulation#6]
Hi,

Thanks for developing this nice package. I wonder how we incorporate phasing information for the founder parents. Is it essentially the order of alleles being formatted in the `allele.file`?

**Comment by vllrs** [comment]
Hello! 
Yes, it is the order of alleles in the `allele.file`: the package will interpret "TA" as being in a different phase to "AT". For each parent in the `allele.file`, the first character in each cell is interpreted as the allele belonging to the first haplotype of that parent, and the second character as belonging to the other haplotype. 
Let me know if you have any issues or other questions.
