### ISSUE TITLE
designate path to output simulated files

### ISSUE THREAD

**Issue by jguo9527** [vllrs/genomicSimulation#7]
The `file.prefix` kind of working in limited layers of directory, but not when the output dir gets complicated.
I wonder if author is thinking of adding an argument to designate the output path, in functions such as `cross.combinations`. Much appreciated!

**Comment by vllrs** [comment]
In my testing, I'm able to put both relative and absolute file paths into `file.prefix` (eg. `file.prefix="../outputdir/myprefix"`, `file.prefix="C:/some/path/myprefix"`). The built-in suffixes (`-bv.txt`, `-pedigree.txt`, etc.) are just appended to `file.prefix`, whether or not it includes a path. Is that the feature you wanted? 

I am happy to make changes, though, if you have improvements in mind. Would you prefer if you could designate the entire path+name of each save-as-you-go output file, over the current `file.prefix` + hardcoded suffix system?

**Comment by jguo9527** [comment]
> In my testing, I'm able to put both relative and absolute file paths into `file.prefix` (eg. `file.prefix="../outputdir/myprefix"`, `file.prefix="C:/some/path/myprefix"`). The built-in suffixes (`-bv.txt`, `-pedigree.txt`, etc.) are just appended to `file.prefix`, whether or not it includes a path. Is that the feature you wanted?
> 
> I am happy to make changes, though, if you have improvements in mind. Would you prefer if you could designate the entire path+name of each save-as-you-go output file, over the current `file.prefix` + hardcoded suffix system?

Thanks for testing that! In my case, I used '~/mydir' for `file.prefix`, which crashed my Rstudio. The absolute and relative paths like yours also worked for me. It could also be something special about my system which I don't have admin power. So it's not an issue really.
